"""evenement model column modification

Revision ID: 11c9e5c7778e
Revises: 1d39869a7493
Create Date: 2025-04-27 21:52:30.126508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '11c9e5c7778e'
down_revision: Union[str, None] = '1d39869a7493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evenement', sa.Column('client_contact_id', sa.String(length=100), nullable=False))
    op.drop_column('evenement', 'client_contact')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evenement', sa.Column('client_contact', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('evenement', 'client_contact_id')
    # ### end Alembic commands ###
