"""Fix Evenements

Revision ID: 581b4b7b5a03
Revises: 8b0c13e5a96b
Create Date: 2025-05-23 11:46:00.773835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '581b4b7b5a03'
down_revision: Union[str, None] = '8b0c13e5a96b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evenement', 'support_id',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Integer(),
               nullable=True)
    op.create_foreign_key(None, 'evenement', 'user', ['support_id'], ['id'])
    op.create_foreign_key(None, 'evenement', 'client', ['client_contact_id'], ['id'])
    op.create_foreign_key(None, 'evenement', 'contrat', ['contrat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evenement', type_='foreignkey')
    op.drop_constraint(None, 'evenement', type_='foreignkey')
    op.drop_constraint(None, 'evenement', type_='foreignkey')
    op.alter_column('evenement', 'support_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
