"""contrat_id, support_id, client_contract_id

Revision ID: 66c0ee8b89ab
Revises: 5cd37b9fc387
Create Date: 2025-05-06 00:39:01.584767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '66c0ee8b89ab'
down_revision: Union[str, None] = '5cd37b9fc387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evenement', sa.Column('support_id', sa.String(length=100), nullable=True))
    op.alter_column('evenement', 'client_contact_id',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_column('evenement', 'support_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evenement', sa.Column('support_name', mysql.VARCHAR(length=100), nullable=True))
    op.alter_column('evenement', 'client_contact_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('evenement', 'support_id')
    # ### end Alembic commands ###
