"""Tables modification

Revision ID: 7164ee67cb6f
Revises: b6435a410058
Create Date: 2025-04-24 20:50:17.707345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7164ee67cb6f'
down_revision: Union[str, None] = 'b6435a410058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('user_contact_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'client', 'user', ['user_contact_id'], ['id'])
    op.drop_column('client', 'contact_name')
    op.create_foreign_key(None, 'contrat', 'user', ['commercial_id'], ['id'])
    op.create_foreign_key(None, 'contrat', 'client', ['client_id'], ['id'])
    op.add_column('user', sa.Column('name', sa.String(length=100), nullable=False))
    op.drop_column('user', 'nom')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nom', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('user', 'name')
    op.drop_constraint(None, 'contrat', type_='foreignkey')
    op.drop_constraint(None, 'contrat', type_='foreignkey')
    op.add_column('client', sa.Column('contact_name', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_column('client', 'user_contact_id')
    # ### end Alembic commands ###
