"""start_date, end_date

Revision ID: c152abe7a3cd
Revises: 66c0ee8b89ab
Create Date: 2025-05-06 01:00:10.482165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c152abe7a3cd'
down_revision: Union[str, None] = '66c0ee8b89ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evenement', 'start_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('evenement', 'end_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evenement', 'end_date',
               existing_type=sa.String(length=100),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('evenement', 'start_date',
               existing_type=sa.String(length=100),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
